name: Build and Deploy Frontend to S3

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Build frontend
        working-directory: frontend
        run: npm run build
        
      - name: Set up AWS CLI for Scaleway
        run: |
          mkdir -p ~/.aws
          echo "[default]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region=${{ secrets.AWS_REGION }}" > ~/.aws/credentials
          echo "[default]
          region=${{ secrets.AWS_REGION }}
          s3 =
            endpoint_url = ${{ secrets.S3_ENDPOINT_URL }}" > ~/.aws/config
            
      - name: Test S3 connection
        run: |
          aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }} --endpoint-url=${{ secrets.S3_ENDPOINT_URL }}
        
      - name: Deploy to S3
        working-directory: frontend
        run: |
          aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} --endpoint-url=${{ secrets.S3_ENDPOINT_URL }} --acl public-read
          
      # - name: Invalidate CloudFront cache (if using CloudFront)
      #   if: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID != '' }}
      #   run: |
      #     aws cloudfront create-invalidation \
      #       --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
      #       --paths "/*"