name: Docker Publish

on:
  push:
    paths:
      - "version.txt" # Trigger only if version.txt changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Sometimes old or cached credentials can cause issues
      - name: Clear Docker config
        run: rm -f ~/.docker/config.json

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image with both tags
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/tsafs/ist-es-gerade-warm:latest -f jobs/job-update-10min-station-data/Dockerfile . 

      # Push both Docker image tags to Docker Hub
      - name: Push Docker image
        run: |
          docker push ghcr.io/tsafs/ist-es-gerade-warm:latest
